// <auto-generated />
namespace LibraryMVC.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BorrowingLogic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BorrowingLogic));
        
        string IMigrationMetadata.Id
        {
            get { return "202008290052388_BorrowingLogic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
